[shell]
program = "/bin/zsh"
args = ["-l"]
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x2c2525"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "0x2c2525"
foreground = "0xfff1f3"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 18

[font.normal]
family = "IosevkaSS 14 Nerd Font"
style = "Extended"

[font.bold]
family = "IosevkaSS 14 Nerd Font"
style = "Extended Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaSS 14 Nerd Font"
style = "Extended Italic"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.95
dynamic_title = true
blur = true

[window.dimensions]
columns = 250
lines = 78

[window.padding]
x = 15
y = 15
