#+title: Doom Emacs Config
#+PROPERTY: header-args :tangle config.el

* TABLE OF CONTENTS :toc:
- [[#intro][Intro]]
  - [[#fonts][Fonts]]
  - [[#themes][Themes]]
  - [[#line-numbers][Line Numbers]]
  - [[#line-breaking][Line Breaking]]
  - [[#transparency][Transparency]]
  - [[#icons][Icons]]
- [[#colemak-mod-dh][Colemak Mod-DH]]
- [[#org-mode][Org-Mode]]
  - [[#org-roam][Org-Roam]]
  - [[#org-latex][Org-Latex]]
- [[#latex-config][LaTeX Config]]
  - [[#bibtex][Bibtex]]
  - [[#snippets][Snippets]]
  - [[#cd-latex][CD-Latex]]
  - [[#folding][Folding]]
- [[#dashboard][Dashboard]]
- [[#dired-ibuffer-sidebar][Dired-iBuffer sidebar]]
- [[#smaller-packages][Smaller Packages]]
  - [[#evil-goggles][Evil Goggles]]
  - [[#daemon][Daemon]]
  - [[#company][Company]]
  - [[#ispell][iSpell]]
  - [[#toggling][Toggling]]
  - [[#openers][Openers]]
  - [[#rainbow-mode][Rainbow Mode]]
  - [[#evil-snipe][Evil Snipe]]
  - [[#other][Other]]

* Intro
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+begin_src elisp
(setq user-full-name "Lucas Kerbs"
      user-mail-address "lucaskerbs@gmail.com")
(setq default-directory "~/Dropbox/Graduate School/")
#+end_src

** Fonts
Doom exposes five (optional) variables for controlling fonts in Doom:
 - `doom-font' -- the primary font to use
 - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
 - `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.
 - `doom-unicode-font' -- for unicode glyphs
 - `doom-serif-font' -- for the `fixed-pitch-serif' face
#+begin_src elisp
(setq doom-font (font-spec :family "JetBrains Mono" :size 14)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 14)
      doom-big-font (font-spec :family "JetBrains Mono" :size 24))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

** Themes
#+begin_src elisp
(setq doom-theme 'doom-monokai-pro)
;;(setq doom-theme 'doom-horizon)
(require 'ewal-doom-themes)
#+end_src

We also want some nice synatx highlighting!
#+begin_src elisp
(use-package! tree-sitter
  :config
  (require 'tree-sitter-langs)
  (global-tree-sitter-mode)
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))
#+end_src

** Line Numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src

** Line Breaking
Break lines (in general text-based documents) automatically at 80-ish lines
#+begin_src elisp
(add-hook 'text-mode-hook  'auto-fill-mode)
(setq-default fill-column 80)
#+end_src

** Transparency
Set the default transparency for active and inactive frames
#+begin_src elisp
(set-frame-parameter (selected-frame) 'alpha '(90 . 75))
(add-to-list 'default-frame-alist '(alpha . (90 . 75)))
#+end_src

** Icons
We want lots of icons!
#+begin_src elisp
(use-package all-the-icons
  :if (display-graphic-p))
;;(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
#+end_src
* Colemak Mod-DH
~evil-colemak-basics~ remaps a number standard evil keymaps. It doesn't play nice
with ~evil-tex~ so first we need some code for that. This code was given from
[[https://github.com/iyefrat/evil-tex/issues/14][Issue 9]] on the ~evil-tex~ page
#+begin_src elisp
(setq evil-tex-toggle-override-m nil)

(with-eval-after-load 'evil-tex
  (evil-define-key 'normal evil-tex-mode-map [remap evil-set-marker]
    (evil-tex-dispatch-single-key ?t #'evil-tex-read-and-execute-toggle
                                  'evil-tex-m-functions)))
#+end_src

Now we load ~evil-colemak-basics~ and create commads so that I can use the
=m-n-e-i= movements between windows
#+begin_src elisp
(require 'evil-colemak-basics)
(use-package evil-colemak-basics
  :config
  (global-evil-colemak-basics-mode)
  )
  (define-key evil-window-map "n" 'evil-window-down)
  (define-key evil-window-map "N" 'evil-window-move-very-bottom)
  (define-key evil-window-map (kbd "C-S-n") 'evil-window-move-very-bottom)
  (define-key evil-window-map "e" 'evil-window-up)
  (define-key evil-window-map "E" 'evil-window-move-very-top)
  (define-key evil-window-map (kbd "C-S-e") 'evil-window-move-very-top)
  (define-key evil-window-map "m" 'evil-window-left)
  (define-key evil-window-map "M" 'evil-window-move-far-left)
  (define-key evil-window-map (kbd "C-S-m") 'evil-window-move-far-left)
  (define-key evil-window-map "i" 'evil-window-right)
  (define-key evil-window-map "I" 'evil-window-move-far-right)
  (define-key evil-window-map (kbd "C-S-i") 'evil-window-move-far-right)
  ;; Kreate new window
  (define-key evil-window-map "k" 'evil-window-new)
  (define-key evil-window-map "\C-k" 'evil-window-new)
#+end_src

* Org-Mode
First we set the default Directories for ~org~ and ~org-roam~
#+begin_src elisp
(setq org-directory "~/Dropbox/Slipbox/")
(setq org-roam-directory "~/Dropbox/Slipbox/")
#+end_src

** Org-Roam

First configure how often org-roam updates itself and the set the default header
for new org-roam documents
#+begin_src elisp
(setq org-roam-db-update-method 'immediate)
(setq org-roam-capture-templates '(("d" "default" plain "%?"
    :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                               "#+title: ${title}\n")
                                :unnarrowed t)))
#+end_src

Next we configure the side-window that is avaliable in org-roam buffers
#+begin_src elisp
(add-to-list 'display-buffer-alist
    '("\\*org-roam\\*"
        (display-buffer-in-side-window)
        (side . right)
        (slot . 0)
        (window-width . 0.25)
        (preserve-size . (t . nil))
        (window-parameters . ((no-other-window . t)
                              (no-delete-other-windows . t)))))
;; (setq org-roam-buffer nil)
#+end_src

** Org-Latex
We want ~cd-latex~ commands avaliable in ~org-mode~ as well as nicer latex highlighting
#+begin_src elisp
(add-hook 'org-mode-hook 'turn-on-org-cdlatex)
 (setq org-highlight-latex-and-related '(latex script entities))
#+end_src

Now turn on ~yas-snippets~ for LaTeX mode in org-buffers
#+begin_src elisp
(defun my-org-latex-yas ()
  (yas-minor-mode)
  (yas-activate-extra-mode 'latex-mode))
(add-hook 'org-mode-hook #'my-org-latex-yas)
#+end_src

Finally, we use ~org-fragtog~ to make the LaTeX snippets automatically toggle
previews
#+begin_src elisp
(add-hook 'org-mode-hook 'org-fragtog-mode)
#+end_src

* LaTeX Config
First we make all the TeX-modes play nice
#+begin_src elisp
(require 'latex)
(add-hook 'latex-mode-hook #'TeX-latex-mode)
#+end_src

I don't like it when emacs adds the braces whenever I add =^= or =_= so that
gets disabled here.
#+begin_src elisp
(setq TeX-electric-sub-and-superscript nil)
#+end_src

** Bibtex
Eventually I'm sure there will be lost more that has to do with my Bibtex
information. For now there is just setting the link to my main =.bib= file
#+begin_src elisp
(setq bibtex-completion-bibliography '("~/Dropbox/Biblio/main.bib"))
#+end_src

When searching with =ivy-bibtex=, we want hitting =RET= on a paper to inset the
LaTeX citation
#+begin_src elisp
(setq ivy-bibtex-default-action 'ivy-bibtex-insert-citation)
#+end_src

** Snippets
This gets certain snippets to expand automatically. Honestly I stole if from
somewher and don't remember where/why.
#+begin_src elisp
(defun my-yas-try-expanding-auto-snippets ()
    (when (and (boundp 'yas-minor-mode) yas-minor-mode)
      (let ((yas-buffer-local-condition ''(require-snippet-condition . auto)))
        (yas-expand))))
  (add-hook 'post-command-hook #'my-yas-try-expanding-auto-snippets)
#+end_src

The package ~laas~ or =latex-auto-activating-snippets= provides the ability to
automatically expand certain snippets with minimal/no input from me.
#+begin_src elisp
(use-package! laas
  :hook (LaTeX-mode . laas-mode)
  ;; if you want it in org-mode too
  :hook (org-mode . laas-mode)
  :config
  (aas-set-snippets 'laas-mode
                    ;; set condition!
                    :cond #'texmathp ; expand only while in math
                    ;;"supp" "\\supp"
                    ;; bind to functions!
                    ;;        (yas-expand-snippet "\\frac{$1}{$2}$0"))
                    "Span" (lambda () (interactive)
                             (yas-expand-snippet "\\Span($1)$0"))))
#+end_src

** CD-Latex
~cd-latex~ is a package that turn the =`= key into a leader key for a bunch of
LaTeX commads. By default Doom turns off it overloading =TAB=, but I've grown
used to it:
#+begin_src elisp
(map! :map cdlatex-mode-map
    :i "TAB" #'cdlatex-tab)
#+end_src

Now we add to the settings under the =`= leader:
#+begin_src elisp
(setq cdlatex-math-symbol-alist
 '(
   ( ?c  ("\\chi"                 "\\circ"                "\\cos"))
   ( ?e  ("\\varepsilon"          "\\epsilon"             "\\exp"))
   ( ?+  ("\\cup"                 "\\oplus"               ""))
   ( ?x  ("\\xi"                  "\\otimes"              ""))
    ))
#+end_src

** Folding
This is just a thing that I am trying---it folds a bunch of the LaTeX commands
to just give symbols when you aren't editing that section
#+begin_src elisp
(after! latex
  (setcar (assoc "⋆" LaTeX-fold-math-spec-list) "★")) ;; make \star bigger
(setq TeX-fold-math-spec-list
      `(;; missing/better symbols
        ("≤" ("le"))
        ("≥" ("ge"))
        ("≠" ("ne"))
        ;; convenience shorts -- these don't work nicely ATM
        ;; ("‹" ("left"))
        ;; ("›" ("right"))
        ;; private macros
        ("ℝ" ("RR"))
        ("ℕ" ("NN"))
        ("ℤ" ("ZZ"))
        ("ℚ" ("QQ"))
        ("ℂ" ("CC"))
        ("ℙ" ("PP"))
        ("ℍ" ("HH"))
        ("𝔼" ("EE"))
        ("𝑑" ("dd"))
        ;; known commands
        ("" ("phantom"))
        (,(lambda (num den) (if (and (TeX-string-single-token-p num) (TeX-string-single-token-p den))
                                (concat num "／" den)
                              (concat "❪" num "／" den "❫"))) ("frac"))
        (,(lambda (arg) (concat "√" (TeX-fold-parenthesize-as-necessary arg))) ("sqrt"))
        (,(lambda (arg) (concat "⭡" (TeX-fold-parenthesize-as-necessary arg))) ("vec"))
        ("‘{1}’" ("text"))
        ;; private commands
        ("|{1}|" ("abs"))
        ("‖{1}‖" ("norm"))
        ("⌊{1}⌋" ("floor"))
        ("⌈{1}⌉" ("ceil"))
        ("⌊{1}⌉" ("round"))
        ("𝑑{1}/𝑑{2}" ("dv"))
        ("∂{1}/∂{2}" ("pdv"))
        ;; fancification
        ("{1}" ("mathrm"))
        (,(lambda (word) (string-offset-roman-chars 119743 word)) ("mathbf"))
        (,(lambda (word) (string-offset-roman-chars 119951 word)) ("mathcal"))
        (,(lambda (word) (string-offset-roman-chars 120003 word)) ("mathfrak"))
        (,(lambda (word) (string-offset-roman-chars 120055 word)) ("mathbb"))
        (,(lambda (word) (string-offset-roman-chars 120159 word)) ("mathsf"))
        (,(lambda (word) (string-offset-roman-chars 120367 word)) ("mathtt"))
        )
      TeX-fold-macro-spec-list
      '(
        ;; as the defaults
        ("[f]" ("footnote" "marginpar"))
        ("[c]" ("cite"))
        ("[l]" ("label"))
        ("[r]" ("ref" "pageref" "eqref"))
        ("[i]" ("index" "glossary"))
        ("..." ("dots"))
        ("{1}" ("emph" "textit" "textsl" "textmd" "textrm" "textsf" "texttt"
                "textbf" "textsc" "textup"))
        ;; tweaked defaults
        ("©" ("copyright"))
        ("®" ("textregistered"))
        ("™"  ("texttrademark"))
        ("[1]:||►" ("item"))
        ("❡❡ {1}" ("part" "part*"))
        ("❡ {1}" ("chapter" "chapter*"))
        ("§ {1}" ("section" "section*"))
        ("§§ {1}" ("subsection" "subsection*"))
        ("§§§ {1}" ("subsubsection" "subsubsection*"))
        ("¶ {1}" ("paragraph" "paragraph*"))
        ("¶¶ {1}" ("subparagraph" "subparagraph*"))
        ;; extra
        ("⬖ {1}" ("begin"))
        ("⬗ {1}" ("end"))
        ))

(defun string-offset-roman-chars (offset word)
  "Shift the codepoint of each character in WORD by OFFSET with an extra -6 shift if the letter is lowercase"
  (apply 'string
         (mapcar (lambda (c)
                   (string-offset-apply-roman-char-exceptions
                    (+ (if (>= c 97) (- c 6) c) offset)))
                 word)))

(defvar string-offset-roman-char-exceptions
  '(;; lowercase serif
    (119892 .  8462) ; ℎ
    ;; lowercase caligraphic
    (119994 . 8495) ; ℯ
    (119996 . 8458) ; ℊ
    (120004 . 8500) ; ℴ
    ;; caligraphic
    (119965 . 8492) ; ℬ
    (119968 . 8496) ; ℰ
    (119969 . 8497) ; ℱ
    (119971 . 8459) ; ℋ
    (119972 . 8464) ; ℐ
    (119975 . 8466) ; ℒ
    (119976 . 8499) ; ℳ
    (119981 . 8475) ; ℛ
    ;; fraktur
    (120070 . 8493) ; ℭ
    (120075 . 8460) ; ℌ
    (120076 . 8465) ; ℑ
    (120085 . 8476) ; ℜ
    (120092 . 8488) ; ℨ
    ;; blackboard
    (120122 . 8450) ; ℂ
    (120127 . 8461) ; ℍ
    (120133 . 8469) ; ℕ
    (120135 . 8473) ; ℙ
    (120136 . 8474) ; ℚ
    (120137 . 8477) ; ℝ
    (120145 . 8484) ; ℤ
    )
  "An alist of deceptive codepoints, and then where the glyph actually resides.")

(defun string-offset-apply-roman-char-exceptions (char)
  "Sometimes the codepoint doesn't contain the char you expect.
Such special cases should be remapped to another value, as given in `string-offset-roman-char-exceptions'."
  (if (assoc char string-offset-roman-char-exceptions)
      (cdr (assoc char string-offset-roman-char-exceptions))
    char))

(defun TeX-fold-parenthesize-as-necessary (tokens &optional suppress-left suppress-right)
  "Add ❪ ❫ parenthesis as if multiple LaTeX tokens appear to be present"
  (if (TeX-string-single-token-p tokens) tokens
    (concat (if suppress-left "" "❪")
            tokens
            (if suppress-right "" "❫"))))

(defun TeX-string-single-token-p (teststring)
  "Return t if TESTSTRING appears to be a single token, nil otherwise"
  (if (string-match-p "^\\\\?\\w+$" teststring) t nil))
#+end_src

* Dashboard
This package makes a nice(r) splash screen than the one that comes with the
default doom. Just in case, let's set the ~doom-dashboard~ image to the one we
want
#+begin_src elisp
(setq fancy-splash-image "~/.doom.d/cute-doom/doom_512.png")
#+end_src

Now we set all the rest of the startup-dashboard
#+begin_src elisp
(use-package dashboard
  :init      ;; tweak dashboard config before loading it
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-set-navigator t)
  (setq dashboard-banner-logo-title "\nKEYBINDINGS:\
\nFind file               (SPC .)     \
Open buffer list    (SPC b i)\
\nFind recent files       (SPC f r)   \
Open the eshell     (SPC e s)\
\nOpen dired file manager (SPC d d)   \
List of keybindings (SPC h b b)")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.doom.d/cute-doom/doom_512.png")
  (setq dashboard-banner-logo-title "Journey Before Destination!")
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (bookmarks . 5)
                          (projects . 3)
                          (registers . 5)))
   :config
   (dashboard-setup-startup-hook)
   (dashboard-modify-heading-icons '((recents . "file-text")
                                     (bookmarks . "book"))))
#+end_src

In the case that we are loading an ~emacsclient~ window, we want to open the
dashboard. Right now it doesn't work right all the time.
#+begin_src elisp
(setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
(setq doom-fallback-buffer "*dashboard*")
#+end_src

* Dired-iBuffer sidebar
Another thing that I am playing with. We create a side-bar with a ~dired~ and
~ibuffer~ window.
#+begin_src elisp
(use-package ibuffer-sidebar
  :load-path "~/.emacs.d/fork/ibuffer-sidebar"
  :commands (ibuffer-sidebar-toggle-sidebar)
  :config
  (setq ibuffer-sidebar-use-custom-font t)
  (setq ibuffer-sidebar-face `(:family "Helvetica" :height 140)))
(use-package dired-sidebar
  :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
  :commands (dired-sidebar-toggle-sidebar)
  :init
  (add-hook 'dired-sidebar-mode-hook
            (lambda ()
              (unless (file-remote-p default-directory)
                (auto-revert-mode))))
  :config
  (push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
  (push 'rotate-windows dired-sidebar-toggle-hidden-commands)

  (setq dired-sidebar-subtree-line-prefix "__")
  (setq dired-sidebar-use-term-integration t)
  (setq dired-sidebar-use-custom-font t))
(defun sidebar-toggle ()
  "Toggle both `dired-sidebar' and `ibuffer-sidebar'."
  (interactive)
  (dired-sidebar-toggle-sidebar)
  (ibuffer-sidebar-toggle-sidebar))
#+end_src
* Smaller Packages
** Evil Goggles
This package adds a little highlight whenever you do a big-boy change
#+begin_src elisp
(use-package evil-goggles
  :init
  (setq evil-goggles-duration 0.1
        evil-goggles-pulse nil ; too slow
        ;; evil-goggles provides a good indicator of what has been affected.
        ;; delete/change is obvious, so I'd rather disable it for these.
        evil-goggles-enable-delete t
        evil-goggles-enable-change t)
  :config
  (evil-goggles-mode)
  (evil-goggles-use-diff-faces))
 #+end_src

** Daemon
We want a simple command to save all buffers and then shutdown the daemon
#+begin_src elisp
(defun server-shutdown ()
  "Save buffers, Quit, and Shutdown (kill) server"
  (interactive)
  (save-some-buffers)
  (kill-emacs)
  )
#+end_src

** Company
Comany is a completion engine. It is really nice but it gets in the way
#+begin_src elisp
(after! company
  (setq company-idle-delay 1.5
       company-minimum-prefix-length 5))
#+end_src

** iSpell
Spell-check needs a home
#+begin_src elisp
(setq ispell-program-name "/usr/local/bin/ispell")
#+end_src

** Toggling
Some simple code that adds things under ~leader-t~ to toggle various things
(once again, this code is stolen and I'm not 100% sure everything it does)
#+begin_src elisp
(map! :leader
      :desc "Comment or uncomment lines" "TAB TAB" #'comment-line
      (:prefix ("t" . "toggle")
       :desc "Toggle line numbers" "l" #'doom/toggle-line-numbers
       :desc "Toggle line highlight in frame" "h" #'hl-line-mode
       :desc "Toggle line highlight globally" "H" #'global-hl-line-mode
       :desc "Toggle truncate lines" "t" #'toggle-truncate-lines))
#+end_src

** Openers
Keybindings to open files that I work with all the time using the find-file
command, which is the interactive file search that opens with ~C-x C-f~ in GNU
Emacs or ~SPC f f~ in Doom Emacs.  These keybindings use find-file
non-interactively since we specify exactly what file to open.  The format I use
for these bindings is ~SPC =~ plus ~key~ since Doom Emacs does not use ~SPC =~.
#+begin_src elisp
(map! :leader
      (:prefix ("=" . "open file")
       :desc "Edit agenda file" "a" #'(lambda () (interactive) (find-file "~/Org/agenda.org"))
       :desc "Edit doom config.org" "c" #'(lambda () (interactive) (find-file "~/.doom.d/config.org"))
       :desc "Edit doom init.el" "i" #'(lambda () (interactive) (find-file "~/.doom.d/init.el"))
       :desc "Edit doom packages.el" "p" #'(lambda () (interactive) (find-file "~/.doom.d/packages.el"))))
#+end_src

** Rainbow Mode
Get those good good colors!
#+begin_src elisp
(define-globalized-minor-mode global-rainbow-mode rainbow-mode
  (lambda () (rainbow-mode 1)))
(global-rainbow-mode 1 )
#+end_src

** Evil Snipe
This is a new thing (as of 4-9-22). It seems like a good way to navigate round
the buffer but I want a little larger range for my sniping
#+begin_src elisp
(after! evil-snipe
  (setq evil-snipe-scope 'visible
        evil-snipe-spillover-scope 'whole-visible))
#+end_src

** Other
These are things that I added at one point but I'm really not sure what is going
on
#+begin_src elisp
(setq projectile-project-search-path '("~/Dropbox/Graduate School/"
                                       "~/Dropbox/PhD Applications/"
                                       "~/Projects/"))
#+end_src
