#!/usr/bin/env sh

limelight -m config width            3
limelight -m config radius           8
limelight -m config placement        interior
limelight -m config active_color     0xFF40FF00
limelight -m config normal_color     0xff555555

echo "limelight configuration loaded.."
