#!/usr/bin/env sh
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m space 1 --label comms
yabai -m space 2 --label code
yabai -m space 3 --label web
yabai -m space 4 --label todo
yabai -m space 5 --label idle
yabai -m space 6 --label music

yabai -m rule --add app="^System Settings$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Timery$" sub-layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^CleanShot X$" sub-layer=above manage=off
yabai -m rule --add app="^CleanMyMac X$" sub-layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off sticky=on sub-layer=above
yabai -m rule --add app="^TeamViewer$" sticky=off sub-layer=above manage=off
yabai -m rule --add app="^Font Book$" sticky=off sub-layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off opacity=0.95
yabai -m rule --add app="^FaceTime$" manage=off sticky=on opacity=0.95
#yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Rocket$" manage=off
yabai -m rule --add app="^Discord$" opacity=1
yabai -m rule --add title="Emacs Everywhere" manage=off opacity=0.95
yabai -m rule --add title="^CustomFileSearch$" manage=off opacity=0.95
yabai -m rule --add title="^Quick Edits" manage=off opacity=0.95
yabai -m rule --add app="Emacs" opacity=1
#yabai -m rule --add title=".*YouTube" opacity=1
yabai -m rule --add title="capture" manage=off opacity=1
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^TV$" opacity=1
yabai -m rule --add app="^Detexify$" opacity=1 manage=off

yabai -m config layout bsp

yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
## set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn
## set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
## set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

yabai -m config window_placement second_child
## yabai -m config window_topmost off
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 10

yabai -m config external_bar all:32:0

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8
yabai -m config window_shadow float

#yabai -m config window_border                on
#yabai -m config window_border_width          4
#yabai -m config window_border_radius         12
#yabai -m config active_window_border_color   0xffff9966
#yabai -m config normal_window_border_color   0xff534c9b

 yabai -m config window_opacity_duration 0.2
 yabai -m config window_animation_duration 0.2

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

## yabai -m signal --add event=window_destroyed action="bash ~/CustomScripts/SwitchSpaces/window-focus-on-destroy.sh"

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &
echo "yabai configuration loaded.."
