[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x2c2525"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "0x2c2525"
foreground = "0xfff1f3"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 15

[font.bold]
family = "JuliaMono"
style = "Bold"


[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JuliaMono"
style = "Italic"

[font.normal]
family = "JuliaMono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.8
dynamic_title = true

[window.dimensions]
columns = 250
lines = 78

[window.padding]
x = 15
y = 15
